version: '3'
services:
  api:
    image: domino-rs
    expose:
      - 8000
    networks:
      - caddy_net

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net

networks:
  caddy_net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
