[package]
name = "backend"
version = "0.4.1"
edition = "2021"

[dependencies]
rocket = {version = "0.5.1", features = ["json"]}
rocket_cors = "0.6.0"
sqlite = "*"
domino-lib = "0.9.8"
rand = "0.8.5"
serde = "*"
