[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "../entity" }
dto = {path = "../dto" }
domino_lib = {path = "../domino_lib"}

[dependencies.sea-orm]
version = "~1.1.1"
features = [
  "runtime-tokio-native-tls",
  "sqlx-sqlite"
]