//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::collection::Entity as Collection;
pub use super::puzzle::Entity as Puzzle;
pub use super::sequence::Entity as Sequence;
pub use super::tile::Entity as Tile;
pub use super::tile_placement::Entity as TilePlacement;
