@startuml domino-app
!pragma teoz true
actor Programmer

actor User

participant Client

box Server
participant Api
box "domino-lib"
    participant Generate
    participant Validate
    participant Classify
    participant Solve
end box
database SqliteDB
end box

group Insertion
    activate Api
    Programmer -> Api: Insert Puzzles
        activate SqliteDB
            loop A certain number of times
            Api -> Generate
            Generate -> Validate
            alt Puzzle is valid
            Validate -> Classify
            Classify -> Solve
            Solve -> Classify
            Classify -> Validate
            Validate -> Generate
            Generate -> Api
            Api -> SqliteDB
            else Puzzle is not valid
            Validate -> Generate 
            Generate -> Api
            end

            end
            SqliteDB -> Api
                alt all went good
                    Api -> Programmer: 200
                else nope
                    Api -> Programmer: 500
                end
        deactivate SqliteDB
    deactivate Api
end

group Selection
    activate Client
        User -> Client: Select Puzzle
        activate Api
            Client -> Api: Select Puzzle
            activate SqliteDB
                Api -> SqliteDB 
                SqliteDB -> Api
                alt all went good
                    Api -> Client: 200 - Puzzle
                else nope
                    Api  -> Client: 500 - There is no puzzle with the features requested
                end
            deactivate SqliteDB
        deactivate Api
        Client -> User
    deactivate Client
end
@enduml