name: Publish Docker Image to GHCR

# Trigger the workflow on push events to main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # Permissions needed for GHCR
    permissions:
      contents: read
      packages: write

    steps:
    # Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to GHCR using docker login with --password-stdin
    - name: Login to GHCR
      run: |
        echo "${{ secrets.GHCR }}" | docker login ghcr.io -u nunzioono --password-stdin

    # Build and push Docker image
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/nunzioono/domino-app:latest
          ghcr.io/nunzioono/domino-app:${{ github.sha }}
