name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    # Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Debug the GHCR secret
    - name: Debug GHCR Secret
      run: |
        echo "Checking if GHCR secret is set..."
        if [ -z "${{ secrets.GHCR }}" ]; then
          echo "ERROR: GHCR secret is empty or not set!"
          exit 1
        else
          echo "SUCCESS: GHCR secret is set (length: ${#GHCR_SECRET})"
          echo "Value is masked, but it exists."
        fi
      env:
        GHCR_SECRET: ${{ secrets.GHCR }}

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to GHCR using docker/login-action
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: nunzioono
        password: ${{ secrets.GHCR }}

    # Build and push Docker image
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/nunzioono/domino-app:latest
          ghcr.io/nunzioono/domino-app:${{ github.sha }}
