//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1
use rocket::serde::{Deserialize, Serialize};
use rocket_okapi::okapi::schemars::{self, JsonSchema};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, FromForm, JsonSchema)]
#[serde(crate = "rocket::serde")]
#[sea_orm(table_name = "collection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub len: i32,
    pub n: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::puzzle::Entity")]
    Puzzle,
    #[sea_orm(has_many = "super::sequence::Entity")]
    Sequence,
    #[sea_orm(has_many = "super::tile_placement::Entity")]
    TilePlacement,
}

impl Related<super::puzzle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Puzzle.def()
    }
}

impl Related<super::sequence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sequence.def()
    }
}

impl Related<super::tile_placement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TilePlacement.def()
    }
}

impl Related<super::tile::Entity> for Entity {
    fn to() -> RelationDef {
        super::tile_placement::Relation::Tile.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tile_placement::Relation::Collection.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
