//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tile")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub left_halve: i32,
    pub right_halve: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tile_placement::Entity")]
    TilePlacement,
}

impl Related<super::tile_placement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TilePlacement.def()
    }
}

impl Related<super::collection::Entity> for Entity {
    fn to() -> RelationDef {
        super::tile_placement::Relation::Collection.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tile_placement::Relation::Tile.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
