//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tile_placement")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub collection_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tile_id: String,
    pub position: i32,
    pub rotation: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::collection::Entity",
        from = "Column::CollectionId",
        to = "super::collection::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Collection,
    #[sea_orm(
        belongs_to = "super::tile::Entity",
        from = "Column::TileId",
        to = "super::tile::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tile,
}

impl Related<super::collection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Collection.def()
    }
}

impl Related<super::tile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
